#pragma once

#include <Eigen/Core>
#include <Eigen/Dense>

#include "TaskData.hpp"
#include "../Definitions.hpp"

class Hotel {

public:
    Hotel(const HistoricalData& historicalData, const TaskData& taskData) :
        mTimesteps(taskData.calculate_timesteps()),	// Used in init & functions
        // Initilaise data vectors with all values to zero
        mTargetLoad_e(historicalData.hotel_eload_data* taskData.Fixed_load1_scalar),
        mTargetHeat_h(historicalData.heatload_data),
        mTargetDHW_h(historicalData.DHWdemand_data)

        //TargetPool_h(Eigen::VectorXf::Zero(BattData.TS_max))
    {
    }

    void AllCalcs(TempSum& tempSum) {
        // Apply demands generated by the hotel to the tempSum values
        tempSum.Heat_h += mTargetHeat_h;
        tempSum.DHW_load_h += mTargetDHW_h;

        tempSum.Elec_e += mTargetLoad_e;
    }


    void Report(FullSimulationResult& Result) {
        // report target load to allow calculation of revenue missed
        Result.Hotel_load = mTargetLoad_e;
        Result.Heatload = mTargetHeat_h + mTargetDHW_h;
    }

private:
    const int mTimesteps;

    year_TS mTargetLoad_e;
    year_TS mTargetHeat_h;
    year_TS mTargetDHW_h;
    //year_TS TargetPool_h;
};