# generated by datamodel-codegen:
#   filename:  SiteRangeSchema.json
#   timestamp: 2025-09-11T12:06:38+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, RootModel


class BatteryModeEnum(str, Enum):
    CONSUME = 'CONSUME'
    CONSUME_PLUS = 'CONSUME_PLUS'


class GasTypeEnum(str, Enum):
    NATURAL_GAS = 'NATURAL_GAS'
    LIQUID_PETROLEUM_GAS = 'LIQUID_PETROLEUM_GAS'


class HeatSourceEnum(str, Enum):
    AMBIENT_AIR = 'AMBIENT_AIR'
    HOTROOM = 'HOTROOM'


class Config(BaseModel):
    capex_limit: float = Field(
        default=2500000,
        description='The maximum capital expenditure (CAPEX) allowed at this site in pounds.',
        ge=0.0,
        title='CAPEX Limit',
    )
    use_boiler_upgrade_scheme: bool = Field(
        default=False,
        description='Apply funding from the boiler upgrade scheme (if eligible).',
        title='Use Boiler Upgrade Scheme',
    )
    general_grant_funding: float = Field(
        default=0,
        description='Apply unconditional funding up to this value in £.',
        ge=0.0,
        title='General Grant Funding',
    )
    npv_time_horizon: int = Field(
        default=10,
        description='The number of years to forecast over for the net-present-value calculations.',
        ge=1,
        title='NPV time horizon',
    )
    npv_discount_factor: float = Field(
        default=0.0,
        description='The decimal discount factor to apply to future years in the net-present-value calculations.',
        title='NPV discount factor',
    )


class Building(BaseModel):
    COMPONENT_IS_MANDATORY: bool = Field(..., title='Mandatory Component')
    scalar_heat_load: list[float] = Field(..., title='Scalar Heat Load')
    scalar_electrical_load: list[float] = Field(..., title='Scalar Electrical Load')
    fabric_intervention_index: list[int] = Field(
        ..., title='Fabric Intervention Index'
    )
    floor_area: float | None = Field(
        default=None,
        description='Floor area of the site in metres squared.',
        gt=0.0,
        title='Floor Area',
    )
    incumbent: bool = Field(
        ...,
        description='Whether this component has already been installed and paid for or not.',
        title='Incumbent',
    )
    age: float = Field(
        ..., description='The age of this component.', ge=0.0, title='Age'
    )
    lifetime: float = Field(
        default=30,
        description='The typical length of time this component will last before it needs replacing.',
        gt=0.0,
        title='Lifetime',
    )


class DataCentre(BaseModel):
    COMPONENT_IS_MANDATORY: bool = Field(..., title='Mandatory Component')
    maximum_load: list[float] = Field(..., title='Maximum Load')
    hotroom_temp: list[float] = Field(..., title='Hotroom Temperature')
    incumbent: bool = Field(
        ...,
        description='Whether this component has already been installed and paid for or not.',
        title='Incumbent',
    )
    age: float = Field(
        ..., description='The age of this component.', ge=0.0, title='Age'
    )
    lifetime: float = Field(
        default=10,
        description='The typical length of time this component will last before it needs replacing.',
        gt=0.0,
        title='Lifetime',
    )


class DomesticHotWater(BaseModel):
    COMPONENT_IS_MANDATORY: bool = Field(..., title='Mandatory Component')
    cylinder_volume: list[float] = Field(..., title='Cylinder Volume')
    incumbent: bool = Field(
        ...,
        description='Whether this component has already been installed and paid for or not.',
        title='Incumbent',
    )
    age: float = Field(
        ..., description='The age of this component.', ge=0.0, title='Age'
    )
    lifetime: float = Field(
        default=12,
        description='The typical length of time this component will last before it needs replacing.',
        gt=0.0,
        title='Lifetime',
    )


class ElectricVehicles(BaseModel):
    COMPONENT_IS_MANDATORY: bool = Field(..., title='Mandatory Component')
    flexible_load_ratio: list[float] = Field(..., title='Flexible Load Ratio')
    small_chargers: list[int] = Field(..., title='Small Chargers')
    fast_chargers: list[int] = Field(..., title='Fast Chargers')
    rapid_chargers: list[int] = Field(..., title='Rapid Chargers')
    ultra_chargers: list[int] = Field(..., title='Ultra Chargers')
    scalar_electrical_load: list[float] = Field(..., title='Scalar Electrical Load')
    incumbent: bool = Field(
        ...,
        description='Whether this component has already been installed and paid for or not.',
        title='Incumbent',
    )
    age: float = Field(
        ..., description='The age of this component.', ge=0.0, title='Age'
    )
    lifetime: float = Field(
        default=15,
        description='The typical length of time this component will last before it needs replacing.',
        gt=0.0,
        title='Lifetime',
    )


class EnergyStorageSystem(BaseModel):
    COMPONENT_IS_MANDATORY: bool = Field(..., title='Mandatory Component')
    capacity: list[float] = Field(..., title='Capacity')
    charge_power: list[float] = Field(..., title='Charge Power')
    discharge_power: list[float] = Field(..., title='Discharge Power')
    battery_mode: list[BatteryModeEnum] = Field(..., title='Battery Mode')
    initial_charge: list[float] = Field(..., title='Initial Charge')
    incumbent: bool = Field(
        ...,
        description='Whether this component has already been installed and paid for or not.',
        title='Incumbent',
    )
    age: float = Field(
        ..., description='The age of this component.', ge=0.0, title='Age'
    )
    lifetime: float = Field(
        default=15,
        description='The typical length of time this component will last before it needs replacing.',
        gt=0.0,
        title='Lifetime',
    )


class GasHeater(BaseModel):
    COMPONENT_IS_MANDATORY: bool = Field(..., title='Mandatory Component')
    maximum_output: list[float] | None = Field(default=None, title='Maximum Output')
    gas_type: list[GasTypeEnum] = Field(..., title='Gas Type')
    boiler_efficiency: list[float] = Field(..., title='Boiler Efficiency')
    fixed_gas_price: float = Field(
        default=0.068,
        description='The price of gas in £/kWh.',
        ge=0.0,
        title='Fixed Gas Price',
    )
    incumbent: bool = Field(
        ...,
        description='Whether this component has already been installed and paid for or not.',
        title='Incumbent',
    )
    age: float = Field(
        ..., description='The age of this component.', ge=0.0, title='Age'
    )
    lifetime: float = Field(
        default=10,
        description='The typical length of time this component will last before it needs replacing.',
        gt=0.0,
        title='Lifetime',
    )


class Grid(BaseModel):
    COMPONENT_IS_MANDATORY: bool = Field(..., title='Mandatory Component')
    grid_export: list[float] = Field(..., title='Grid Export')
    grid_import: list[float] = Field(..., title='Grid Import')
    import_headroom: list[float] = Field(..., title='Import Headroom')
    tariff_index: list[int] = Field(..., title='Tariff Index')
    export_tariff: list[float] | None = Field(default=None, title='Export Tariff')
    incumbent: bool = Field(
        ...,
        description='Whether this component has already been installed and paid for or not.',
        title='Incumbent',
    )
    age: float = Field(
        ..., description='The age of this component.', ge=0.0, title='Age'
    )
    lifetime: float = Field(
        default=25,
        description='The typical length of time this component will last before it needs replacing.',
        gt=0.0,
        title='Lifetime',
    )


class HeatPump(BaseModel):
    COMPONENT_IS_MANDATORY: bool = Field(..., title='Mandatory Component')
    heat_power: list[float] = Field(..., title='Heat Power')
    heat_source: list[HeatSourceEnum] = Field(..., title='Heat Source')
    send_temp: list[float] = Field(..., title='Send Temperature')
    incumbent: bool = Field(
        ...,
        description='Whether this component has already been installed and paid for or not.',
        title='Incumbent',
    )
    age: float = Field(
        ..., description='The age of this component.', ge=0.0, title='Age'
    )
    lifetime: float = Field(
        default=10,
        description='The typical length of time this component will last before it needs replacing.',
        gt=0.0,
        title='Lifetime',
    )


class Mop(BaseModel):
    COMPONENT_IS_MANDATORY: bool = Field(..., title='Mandatory Component')
    maximum_load: list[float] = Field(..., title='Maximum Load')
    incumbent: bool = Field(
        ...,
        description='Whether this component has already been installed and paid for or not.',
        title='Incumbent',
    )
    age: float = Field(
        ..., description='The age of this component.', ge=0.0, title='Age'
    )
    lifetime: float = Field(
        default=10,
        description='The typical length of time this component will last before it needs replacing.',
        gt=0.0,
        title='Lifetime',
    )


class SolarPanel(BaseModel):
    COMPONENT_IS_MANDATORY: bool = Field(default=True, title='Mandatory Component')
    yield_scalar: list[float]
    yield_index: list[int] = Field(
        title='Yield Index',
    )
    incumbent: bool = Field(
        ...,
        description='Whether this component has already been installed and paid for or not.',
        title='Incumbent',
    )
    age: float = Field(
        ..., description='The age of this component.', ge=0.0, title='Age'
    )
    lifetime: float = Field(
        default=25,
        description='The typical length of time this component will last before it needs replacing.',
        gt=0.0,
        title='Lifetime',
    )


class SiteRange(BaseModel):
    building: Building | None = Field(default=None, title='Building')
    data_centre: DataCentre | None = Field(default=None, title='Data Centre')
    domestic_hot_water: DomesticHotWater | None = Field(
        default=None, title='Domestic Hot Water'
    )
    electric_vehicles: ElectricVehicles | None = Field(
        default=None, title='EV Chargers'
    )
    energy_storage_system: EnergyStorageSystem | None = Field(
        default=None, title='Energy Storage System'
    )
    gas_heater: GasHeater | None = Field(default=None, title='Gas Heater')
    grid: Grid | None = Field(default=None, title='Grid')
    heat_pump: HeatPump | None = Field(default=None, title='Heat Pump')
    mop: Mop | None = Field(default=None, title='Mop')
    solar_panels: list[SolarPanel] | None = None
    config: Config = Field(..., title='Config')
