# generated by datamodel-codegen:
#   filename:  TaskDataSchema.json
#   timestamp: 2025-09-11T12:06:30+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field

from ..epl_typing import Jsonable

class Building(BaseModel):
    scalar_heat_load: float = Field(
        default=1.0,
        description='Scalar multiplier applied to the baseline heat load.',
        ge=0.0,
        title='Scalar Heat Load',
    )
    scalar_electrical_load: float = Field(
        default=1.0,
        description='Scalar multiplier applied to the baseline electrical load.',
        ge=0.0,
        title='Scalar Electrical Load',
    )
    fabric_intervention_index: int = Field(
        default=0,
        description='Index mapping to a fabric intervention option specified in the SiteData.',
        ge=0,
        title='Fabric Intervention Index',
    )
    floor_area: float | None = Field(
        default=None,
        description='Floor area of the site in metres squared.',
        gt=0.0,
        title='Floor Area',
    )
    incumbent: bool = Field(
        default=False,
        description='Whether this component has already been installed and paid for or not.',
        title='Incumbent',
    )
    age: float = Field(
        default=0, description='The age of this component.', ge=0.0, title='Age'
    )
    lifetime: float = Field(
        default=30,
        description='The typical length of time this component will last before it needs replacing.',
        gt=0.0,
        title='Lifetime',
    )


class DataCentre(BaseModel):
    maximum_load: float = Field(
        default=50.0,
        description='The maximum load for the Data Centre in kW',
        ge=0.0,
        title='Maximum Load',
    )
    hotroom_temp: float = Field(
        default=43.0,
        description='Operating temperature of the Data Centre in degrees Celsius.',
        title='Hotroom Temperature',
    )
    incumbent: bool = Field(
        default=False,
        description='Whether this component has already been installed and paid for or not.',
        title='Incumbent',
    )
    age: float = Field(
        default=0, description='The age of this component.', ge=0.0, title='Age'
    )
    lifetime: float = Field(
        default=10,
        description='The typical length of time this component will last before it needs replacing.',
        gt=0.0,
        title='Lifetime',
    )


class DomesticHotWater(BaseModel):
    cylinder_volume: float = Field(
        default=100.0,
        description='The volume of the cylinder in metres cubed',
        ge=0.0,
        title='Cylinder Volume',
    )
    incumbent: bool = Field(
        default=False,
        description='Whether this component has already been installed and paid for or not.',
        title='Incumbent',
    )
    age: float = Field(
        default=0, description='The age of this component.', ge=0.0, title='Age'
    )
    lifetime: float = Field(
        default=12,
        description='The typical length of time this component will last before it needs replacing.',
        gt=0.0,
        title='Lifetime',
    )


class ElectricVehicles(BaseModel):
    flexible_load_ratio: float = Field(
        default=0.5,
        description='The decimal fraction of the load that must be met.',
        ge=0.0,
        le=1.0,
        title='Flexible Load Ratio',
    )
    small_chargers: int = Field(
        default=0,
        description='The quantity of small chargers.',
        ge=0,
        title='Small Chargers',
    )
    fast_chargers: int = Field(
        default=3,
        description='The quantity of fast chargers.',
        ge=0,
        title='Fast Chargers',
    )
    rapid_chargers: int = Field(
        default=0,
        description='The quantity of rapid chargers.',
        ge=0,
        title='Rapid Chargers',
    )
    ultra_chargers: int = Field(
        default=0,
        description='The quantity of ultra chargers.',
        ge=0,
        title='Ultra Chargers',
    )
    scalar_electrical_load: float = Field(
        default=3.0,
        description='Scalar multiplier for the EV Charging load.',
        ge=0.0,
        title='Scalar Electrical Load',
    )
    incumbent: bool = Field(
        default=False,
        description='Whether this component has already been installed and paid for or not.',
        title='Incumbent',
    )
    age: float = Field(
        default=0, description='The age of this component.', ge=0.0, title='Age'
    )
    lifetime: float = Field(
        default=15,
        description='The typical length of time this component will last before it needs replacing.',
        gt=0.0,
        title='Lifetime',
    )


class BatteryMode(str, Enum):
    CONSUME = 'CONSUME'
    CONSUME_PLUS = 'CONSUME_PLUS'


class EnergyStorageSystem(BaseModel):
    capacity: float = Field(
        default=20.0, description='Battery capacity in kWh.', gt=0.0, title='Capacity'
    )
    charge_power: float = Field(
        default=10.0,
        description='Instantaneous charge power in kW.',
        gt=0.0,
        title='Charge Power',
    )
    discharge_power: float = Field(
        default=10.0,
        description='Instantaneous discharge power in kW.',
        gt=0.0,
        title='Discharge Power',
    )
    battery_mode: BatteryMode = Field(
        default='CONSUME',
        description='The algorithmic mode that determines when the battery charges/discharges.',
        title='Battery Mode',
    )
    initial_charge: float = Field(
        default=0.0,
        description='Initial charge of the battery in kWh.',
        ge=0.0,
        title='Initial Charge',
    )
    incumbent: bool = Field(
        default=False,
        description='Whether this component has already been installed and paid for or not.',
        title='Incumbent',
    )
    age: float = Field(
        default=0, description='The age of this component.', ge=0.0, title='Age'
    )
    lifetime: float = Field(
        default=15,
        description='The typical length of time this component will last before it needs replacing.',
        gt=0.0,
        title='Lifetime',
    )


class GasType(str, Enum):
    NATURAL_GAS = 'NATURAL_GAS'
    LIQUID_PETROLEUM_GAS = 'LIQUID_PETROLEUM_GAS'


class GasHeater(BaseModel):
    maximum_output: float = Field(
        default=40.0,
        description='The maximum heat output in kW.',
        gt=0.0,
        title='Maximum Output',
    )
    gas_type: GasType = Field(
        default='NATURAL_GAS',
        description='The type of gas used to power this boiler.',
        title='Gas Type',
    )
    boiler_efficiency: float = Field(
        default=0.9,
        description='The decimal efficiency of the boiler.',
        gt=0.0,
        le=1.0,
        title='Boiler Efficiency',
    )
    fixed_gas_price: float = Field(
        default=0.068,
        description='The price of gas in £/kWh.',
        ge=0.0,
        title='Fixed Gas Price',
    )
    incumbent: bool = Field(
        default=False,
        description='Whether this component has already been installed and paid for or not.',
        title='Incumbent',
    )
    age: float = Field(
        default=0, description='The age of this component.', ge=0.0, title='Age'
    )
    lifetime: float = Field(
        default=10,
        description='The typical length of time this component will last before it needs replacing.',
        gt=0.0,
        title='Lifetime',
    )


class Grid(BaseModel):
    grid_export: float = Field(
        default=23.0,
        description='The maximum power the grid can export in kW.',
        ge=0.0,
        title='Grid Export',
    )
    grid_import: float = Field(
        default=23.0,
        description='The maximum power the grid can import in kW.',
        ge=0.0,
        title='Grid Import',
    )
    import_headroom: float = Field(
        default=0.25,
        description='The decimal fraction of the peak electrical load that must be reserved.',
        ge=0.0,
        le=1.0,
        title='Import Headroom',
    )
    tariff_index: int = Field(
        default=0,
        description='Index mapping to an electricity tariff option defined within SiteData.',
        ge=0,
        title='Tariff Index',
    )
    export_tariff: float = Field(
        default=0.05,
        description='Fixed price export tariff in £/kWh.',
        title='Export Tariff',
    )
    incumbent: bool = Field(
        default=False,
        description='Whether this component has already been installed and paid for or not.',
        title='Incumbent',
    )
    age: float = Field(
        default=0, description='The age of this component.', ge=0.0, title='Age'
    )
    lifetime: float = Field(
        default=25,
        description='The typical length of time this component will last before it needs replacing.',
        gt=0.0,
        title='Lifetime',
    )


class HeatSource(str, Enum):
    AMBIENT_AIR = 'AMBIENT_AIR'
    HOTROOM = 'HOTROOM'


class HeatPump(BaseModel):
    heat_power: float = Field(
        default=20.0,
        description='The maximum power output this heat pump can produce in kW.',
        ge=0.0,
        title='Heat Power',
    )
    heat_source: HeatSource = Field(
        default='AMBIENT_AIR',
        description='The source of the air the heat pump draws from.',
        title='Heat Source',
    )
    send_temp: float = Field(
        default=70.0,
        description='The flow temperature the heat pump operates at in degrees Celsius.',
        title='Send Temperature',
    )
    incumbent: bool = Field(
        default=False,
        description='Whether this component has already been installed and paid for or not.',
        title='Incumbent',
    )
    age: float = Field(
        default=0, description='The age of this component.', ge=0.0, title='Age'
    )
    lifetime: float = Field(
        default=10,
        description='The typical length of time this component will last before it needs replacing.',
        gt=0.0,
        title='Lifetime',
    )


class Mop(BaseModel):
    maximum_load: float = Field(
        default=300.0,
        description='The maximum heat power this component will draw in kW.',
        ge=0.0,
        title='Maximum Load',
    )
    incumbent: bool = Field(
        default=False,
        description='Whether this component has already been installed and paid for or not.',
        title='Incumbent',
    )
    age: float = Field(
        default=0, description='The age of this component.', ge=0.0, title='Age'
    )
    lifetime: float = Field(
        default=10,
        description='The typical length of time this component will last before it needs replacing.',
        gt=0.0,
        title='Lifetime',
    )


class SolarPanel(BaseModel):
    yield_scalar: float = Field(
        default=20.0,
        description='The peak solar generation capability of these panels in kW.',
        ge=0.0,
        title='Yield Scalar',
    )
    yield_index: int = Field(
        default=0,
        description='Index mapping to a solar yield array in SiteData.',
        ge=0,
        title='Yield Index',
    )
    incumbent: bool = Field(
        default=False,
        description='Whether this component has already been installed and paid for or not.',
        title='Incumbent',
    )
    age: float = Field(
        default=0, description='The age of this component.', ge=0.0, title='Age'
    )
    lifetime: float = Field(
        default=25,
        description='The typical length of time this component will last before it needs replacing.',
        gt=0.0,
        title='Lifetime',
    )


class TaskData(BaseModel):
    building: Building | None = Field(
        default=None,
        description='A component to represent the physical building structure and its usage demands.',
        title='Building',
    )
    data_centre: DataCentre | None = Field(
        default=None, description='A Data Centre', title='Data Centre'
    )
    domestic_hot_water: DomesticHotWater | None = Field(
        default=None, title='Domestic Hot Water'
    )
    electric_vehicles: ElectricVehicles | None = Field(
        default=None, title='EV Chargers'
    )
    energy_storage_system: EnergyStorageSystem | None = Field(
        default=None, title='Energy Storage System'
    )
    gas_heater: GasHeater | None = Field(default=None, title='Gas Heater')
    grid: Grid | None = Field(default=None, title='Grid')
    heat_pump: HeatPump | None = Field(default=None, title='Heat Pump')
    mop: Mop | None = Field(
        default=None,
        description='A generic component to consume excess heat.',
        title='Mop',
    )
    solar_panels: list[SolarPanel] | None = Field(default=None, title='Solar Panels')
