# Use Python 3.12 slim image
FROM python:latest

# Set working directory in the container
# WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 8762

# Command to run the application
CMD ["fastapi", "run", "./app/main.py", "--port", "8762"]