FROM astral/uv:python3.13-trixie-slim

WORKDIR /app

ENV UV_COMPILE_BYTECODE=1

# Copy requirements
COPY uv.lock pyproject.toml ./

# Install deps
RUN uv sync --frozen --no-dev

# Copy the rest of the application code
COPY data_service/ ./

# Expose the port the app runs on
EXPOSE 8762

# Command to run the application
CMD ["uv", "run", "fastapi", "run", "./app/main.py", "--host", "0.0.0.0", "--port", "8762"]
